### ISSUE TITLE
Unsupported value: NaN

### ISSUE THREAD

**Issue by johnnyasantoss** [sgarciac/fuego#33]
Error happening when exporting a NaN value. Not sure how to map that to a json file but, I think that null should be fine.

**Comment by johnnyasantoss** [comment]
Forgot to say what I was doing to receive this error: Trying to query an collection with a NaN value in its documents.

**Comment by sgarciac** [comment]
Hello @johnnyasantoss  , thanks!

**Comment by sgarciac** [comment]
@johnnyasantoss I just pushed a fix for this issue, transforming NaNs to nulls as you suggested, before printing them. If you are able to build fuego, it'd be nice if you could test it against your case (setting up an example is not straight-forward, as I can not writer a NaN value with fuego or the web UI...).

**Comment by johnnyasantoss** [comment]
Wow, that was a fast fix. Go is not my specialty, but I'll try to build it locally and test it again. Thanks!

**Comment by johnnyasantoss** [comment]
I've built it locally using ```sudo docker run --rm -it -v `pwd`:/app/ -w /app golang:stretch go build .```, but the bug still there. Tried to query a whole collection (where there are NaNs) piping the output to a file but it crashed with the same error. 

Just to be sure: the fix is on master, right?

**Comment by sgarciac** [comment]
@johnnyasantoss yeah, it's on master. Ok, thanks a lot, I will have to reproduce the bug and have a deeper look at this issue.

**Comment by sgarciac** [comment]
Hi @johnnyasantoss , I had a bug in my fix :facepalm:, I think it should be good know. At least it passed my tests!

**Comment by johnnyasantoss** [comment]
It works now. Just built the last version, and it worked perfectly. Again, thank you for this great program :smile:
